# Strategy Benchmark

Extracts the top-N best performing strategies from `model_comparison_results.csv` (fine-tuned models only), then re-runs each on the FinAgent benchmark stocks and date range.

**Reusable**: re-run this notebook any time `model_comparison_results.csv` is updated — it always picks up the latest best strategies.

### Installations

In [105]:
%pip install backtrader alpaca_trade_api plotly pandas -q

Note: you may need to restart the kernel to use updated packages.

### Config

In [106]:
ALPACA_API_KEY    = ''
ALPACA_SECRET_KEY = ''

RESULTS_CSV       = 'model_comparison_results_merged.csv'

# FinAgent benchmark
BENCHMARK_SYMBOLS = ['AAPL', 'AMZN', 'MSFT', 'TSLA', 'GOOGL']
BENCHMARK_START   = '2022-06-01'
BENCHMARK_END     = '2024-01-01'

# Which fine-tuned models to extract strategies from
TARGET_MODELS = [
    'Qwen2.5-7B LoRA v1-500',
    'Llama-3.1-8B LoRA v1-500',
    'Qwen2.5-32B LoRA v1-500',
]

# How many top strategies to extract per model (ranked by return_pct)
TOP_N = 10

### Imports & Backtrader

In [107]:
import ast
import json
import re
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FuturesTimeout

import backtrader as bt
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from alpaca_trade_api.rest import REST, TimeFrame

In [108]:
class Backtrader:
    _data_cache = {}

    def __init__(self):
        self.rest_api = REST(
            ALPACA_API_KEY, ALPACA_SECRET_KEY,
            'https://paper-api.alpaca.markets'
        )

    def _get_bars(self, symbol, start, end):
        key = (symbol, start, end)
        if key not in Backtrader._data_cache:
            Backtrader._data_cache[key] = self.rest_api.get_bars(
                symbol, TimeFrame.Day, start, end, adjustment='all'
            ).df
        return Backtrader._data_cache[key]

    def prefetch(self, symbols, start, end):
        print(f'Pre-fetching {len(symbols)} symbols ({start} to {end})...')
        for i, sym in enumerate(symbols, 1):
            self._get_bars(sym, start, end)
            print(f'  [{i}/{len(symbols)}] {sym}')
        print('Done.')

    def run_backtest(self, strategy_cls, symbol, start, end, cash=10000):
        cerebro = bt.Cerebro(stdstats=True)
        cerebro.broker.setcash(cash)
        cerebro.addstrategy(strategy_cls)
        cerebro.addanalyzer(bt.analyzers.SharpeRatio,  _name='sharpe')
        cerebro.addanalyzer(bt.analyzers.AnnualReturn, _name='annual')
        cerebro.addanalyzer(bt.analyzers.DrawDown,     _name='drawdown')
        cerebro.adddata(bt.feeds.PandasData(
            dataname=self._get_bars(symbol, start, end), name=symbol
        ))
        init_val = cerebro.broker.getvalue()
        results  = cerebro.run()
        ret      = (cerebro.broker.getvalue() / init_val - 1) * 100
        strat    = results[0]
        sharpe   = strat.analyzers.sharpe.get_analysis().get('sharperatio')
        annual   = strat.analyzers.annual.get_analysis()
        avg_ann  = (sum(annual.values()) / len(annual) * 100) if annual else 0.0
        max_dd   = strat.analyzers.drawdown.get_analysis()['max']['drawdown']
        return ret, sharpe, avg_ann, max_dd

    def timed_backtest(self, strategy_cls, symbol, start, end, timeout=10):
        with ThreadPoolExecutor(max_workers=1) as ex:
            future = ex.submit(self.run_backtest, strategy_cls, symbol, start, end)
            try:
                return future.result(timeout=timeout)
            except FuturesTimeout:
                raise TimeoutError(f'Backtest timed out ({symbol})')


bt_instance = Backtrader()
bt_instance.prefetch(BENCHMARK_SYMBOLS, BENCHMARK_START, BENCHMARK_END)

Pre-fetching 5 symbols (2022-06-01 to 2024-01-01)...
  [1/5] AAPL
  [2/5] AMZN
  [3/5] MSFT
  [4/5] TSLA
  [5/5] GOOGL
Done.

### Extract Best Strategies from CSV

In [109]:
df_results = pd.read_csv(RESULTS_CSV)

extracted = []
for model in TARGET_MODELS:
    for symbol in BENCHMARK_SYMBOLS:
        candidates = df_results[
            (df_results['model']         == model)  &
            (df_results['symbol']        == symbol) &
            (df_results['status']        == 'profitable') &
            (df_results['strategy_code'].notna())
        ].sort_values('avg_annual_return_pct', ascending=False)

        if candidates.empty:
            print(f'  SKIP {model} [{symbol}]: no profitable strategies found')
            continue

        for rank, (_, row) in enumerate(candidates.head(TOP_N).iterrows(), 1):
            extracted.append({
                'model':      model,
                'symbol':     symbol,
                'rank':       rank,
                'origin_arr': row['avg_annual_return_pct'],
                'origin_shr': row['sharpe_ratio'],
                'code':       row['strategy_code'],
                'label':      f"{model} [{symbol}] #{rank}",
            })

print(f'\nExtracted {len(extracted)} candidates (top {TOP_N} per model × symbol):\n')
for s in extracted:
    print(f"  {s['label']}  origin ARR={s['origin_arr']:.1f}%")

  SKIP Llama-3.1-8B LoRA v1-500 [AAPL]: no profitable strategies found

Extracted 100 candidates (top 10 per model × symbol):

  Qwen2.5-7B LoRA v1-500 [AAPL] #1  origin ARR=11.3%
  Qwen2.5-7B LoRA v1-500 [AAPL] #2  origin ARR=11.3%
  Qwen2.5-7B LoRA v1-500 [AAPL] #3  origin ARR=7.8%
  Qwen2.5-7B LoRA v1-500 [AAPL] #4  origin ARR=5.7%
  Qwen2.5-7B LoRA v1-500 [AAPL] #5  origin ARR=5.7%
  Qwen2.5-7B LoRA v1-500 [AAPL] #6  origin ARR=5.7%
  Qwen2.5-7B LoRA v1-500 [AAPL] #7  origin ARR=5.6%
  Qwen2.5-7B LoRA v1-500 [AAPL] #8  origin ARR=2.9%
  Qwen2.5-7B LoRA v1-500 [AMZN] #1  origin ARR=14.9%
  Qwen2.5-7B LoRA v1-500 [AMZN] #2  origin ARR=14.9%
  Qwen2.5-7B LoRA v1-500 [AMZN] #3  origin ARR=14.9%
  Qwen2.5-7B LoRA v1-500 [AMZN] #4  origin ARR=14.1%
  Qwen2.5-7B LoRA v1-500 [AMZN] #5  origin ARR=10.6%
  Qwen2.5-7B LoRA v1-500 [AMZN] #6  origin ARR=5.6%
  Qwen2.5-7B LoRA v1-500 [AMZN] #7  origin ARR=4.8%
  Qwen2.5-7B LoRA v1-500 [MSFT] #1  origin ARR=14.7%
  Qwen2.5-7B LoRA v1-500 [MSFT] #2  origin ARR=14.7%
  Qwen2.5-7B LoRA v1-500 [MSFT] #3  origin ARR=14.7%
  Qwen2.5-7B LoRA v1-500 [MSFT] #4  origin ARR=14.2%
  Qwen2.5-7B LoRA v1-500 [MSFT] #5  origin ARR=14.0%
  Qwen2.5-7B LoRA v1-500 [MSFT] #6  origin ARR=14.0%
  Qwen2.5-7B LoRA v1-500 [MSFT] #7  origin ARR=4.8%
  Qwen2.5-7B LoRA v1-500 [TSLA] #1  origin ARR=15.4%
  Qwen2.5-7B LoRA v1-500 [TSLA] #2  origin ARR=9.5%
  Qwen2.5-7B LoRA v1-500 [TSLA] #3  origin ARR=9.5%
  Qwen2.5-7B LoRA v1-500 [TSLA] #4  origin ARR=9.5%
  Qwen2.5-7B LoRA v1-500 [TSLA] #5  origin ARR=9.5%
  Qwen2.5-7B LoRA v1-500 [TSLA] #6  origin ARR=7.5%
  Qwen2.5-7B LoRA v1-500 [TSLA] #7  origin ARR=6.4%
  Qwen2.5-7B LoRA v1-500 [TSLA] #8  origin ARR=3.4%
  Qwen2.5-7B LoRA v1-500 [GOOGL] #1  origin ARR=23.1%
  Qwen2.5-7B LoRA v1-500 [GOOGL] #2  origin ARR=21.8%
  Qwen2.5-7B LoRA v1-500 [GOOGL] #3  origin ARR=21.4%
  Qwen2.5-7B LoRA v1-500 [GOOGL] #4  origin ARR=20.4%
  Qwen2.5-7B LoRA v1-500 [GOOGL] #5  origin ARR=20.4%
  Qwen2.5-7B LoRA v1-500 [GOOGL] #6  origin ARR=20.4%
  Qwen2.5-7B LoRA v1-500 [GOOGL] #7  origin ARR=16.2%
  Qwen2.5-7B LoRA v1-500 [GOOGL] #8  origin ARR=14.7%
  Qwen2.5-7B LoRA v1-500 [GOOGL] #9  origin ARR=9.1%
  Llama-3.1-8B LoRA v1-500 [AMZN] #1  origin ARR=0.2%
  Llama-3.1-8B LoRA v1-500 [AMZN] #2  origin ARR=0.2%
  Llama-3.1-8B LoRA v1-500 [MSFT] #1  origin ARR=5.9%
  Llama-3.1-8B LoRA v1-500 [MSFT] #2  origin ARR=0.1%
  Llama-3.1-8B LoRA v1-500 [TSLA] #1  origin ARR=43.9%
  Llama-3.1-8B LoRA v1-500 [TSLA] #2  origin ARR=27.1%
  Llama-3.1-8B LoRA v1-500 [TSLA] #3  origin ARR=2.0%
  Llama-3.1-8B LoRA v1-500 [TSLA] #4  origin ARR=0.4%
  Llama-3.1-8B LoRA v1-500 [TSLA] #5  origin ARR=0.3%
  Llama-3.1-8B LoRA v1-500 [GOOGL] #1  origin ARR=15.0%
  Llama-3.1-8B LoRA v1-500 [GOOGL] #2  origin ARR=0.3%
  Qwen2.5-32B LoRA v1-500 [AAPL] #1  origin ARR=15.7%
  Qwen2.5-32B LoRA v1-500 [AAPL] #2  origin ARR=15.7%
  Qwen2.5-32B LoRA v1-500 [AAPL] #3  origin ARR=15.7%
  Qwen2.5-32B LoRA v1-500 [AAPL] #4  origin ARR=15.7%
  Qwen2.5-32B LoRA v1-500 [AAPL] #5  origin ARR=15.7%
  Qwen2.5-32B LoRA v1-500 [AAPL] #6  origin ARR=14.1%
  Qwen2.5-32B LoRA v1-500 [AAPL] #7  origin ARR=11.3%
  Qwen2.5-32B LoRA v1-500 [AAPL] #8  origin ARR=10.4%
  Qwen2.5-32B LoRA v1-500 [AAPL] #9  origin ARR=8.3%
  Qwen2.5-32B LoRA v1-500 [AAPL] #10  origin ARR=6.6%
  Qwen2.5-32B LoRA v1-500 [AMZN] #1  origin ARR=20.8%
  Qwen2.5-32B LoRA v1-500 [AMZN] #2  origin ARR=20.4%
  Qwen2.5-32B LoRA v1-500 [AMZN] #3  origin ARR=20.4%
  Qwen2.5-32B LoRA v1-500 [AMZN] #4  origin ARR=20.2%
  Qwen2.5-32B LoRA v1-500 [AMZN] #5  origin ARR=19.9%
  Qwen2.5-32B LoRA v1-500 [AMZN] #6  origin ARR=19.9%
  Qwen2.5-32B LoRA v1-500 [AMZN] #7  origin ARR=19.7%
  Qwen2.5-32B LoRA v1-500 [AMZN] #8  origin ARR=19.0%
  Qwen2.5-32B LoRA v1-500 [AMZN] #9  origin ARR=14.4%
  Qwen2.5-32B LoRA v1-500 [AMZN] #10  origin ARR=11.6%
  Qwen2.5-32B LoRA v1-500 [MSFT] #1  origin ARR=20.3%
  Qwen2.5-32B LoRA v1-500 [MSFT] #2  origin ARR=20.3%
  Qwen2.5-32B LoRA v1-500 [MSFT] #3  origin ARR=18.7%
  Qwen2.5-32B LoRA v1-500 [MSFT] #4  origin ARR=16.0%
  Qwen2.5-32B LoRA v1-500 [MSFT] #5  origin ARR=16.0%
  Qwen2.5-32B LoRA v1-500 [MSFT] #6  origin ARR=15.4%
  Qwen2.5-32B LoRA v1-500 [MSFT] #7  origin ARR=15.4%
  Qwen2.5-32B LoRA v1-500 [MSFT] #8  origin ARR=13.1%
  Qwen2.5-32B LoRA v1-500 [MSFT] #9  origin ARR=10.5%
  Qwen2.5-32B LoRA v1-500 [MSFT] #10  origin ARR=6.7%
  Qwen2.5-32B LoRA v1-500 [TSLA] #1  origin ARR=32.2%
  Qwen2.5-32B LoRA v1-500 [TSLA] #2  origin ARR=27.3%
  Qwen2.5-32B LoRA v1-500 [TSLA] #3  origin ARR=25.9%
  Qwen2.5-32B LoRA v1-500 [TSLA] #4  origin ARR=25.9%
  Qwen2.5-32B LoRA v1-500 [TSLA] #5  origin ARR=25.9%
  Qwen2.5-32B LoRA v1-500 [TSLA] #6  origin ARR=25.9%
  Qwen2.5-32B LoRA v1-500 [TSLA] #7  origin ARR=25.4%
  Qwen2.5-32B LoRA v1-500 [TSLA] #8  origin ARR=25.4%
  Qwen2.5-32B LoRA v1-500 [TSLA] #9  origin ARR=16.2%
  Qwen2.5-32B LoRA v1-500 [TSLA] #10  origin ARR=12.1%
  Qwen2.5-32B LoRA v1-500 [GOOGL] #1  origin ARR=38.9%
  Qwen2.5-32B LoRA v1-500 [GOOGL] #2  origin ARR=30.8%
  Qwen2.5-32B LoRA v1-500 [GOOGL] #3  origin ARR=30.8%
  Qwen2.5-32B LoRA v1-500 [GOOGL] #4  origin ARR=30.8%
  Qwen2.5-32B LoRA v1-500 [GOOGL] #5  origin ARR=30.8%
  Qwen2.5-32B LoRA v1-500 [GOOGL] #6  origin ARR=30.5%
  Qwen2.5-32B LoRA v1-500 [GOOGL] #7  origin ARR=21.5%
  Qwen2.5-32B LoRA v1-500 [GOOGL] #8  origin ARR=21.4%
  Qwen2.5-32B LoRA v1-500 [GOOGL] #9  origin ARR=18.4%
  Qwen2.5-32B LoRA v1-500 [GOOGL] #10  origin ARR=17.8%

### Run on Benchmark Symbols

In [110]:
def load_strategy(code):
    namespace = {'bt': bt}
    exec(code, namespace)
    return namespace['Strategy']


all_results = []

for strat_info in extracted:
    symbol = strat_info['symbol']
    try:
        strategy_cls = load_strategy(strat_info['code'])
    except Exception as e:
        print(f"LOAD ERROR {strat_info['label']}: {e}")
        all_results.append({
            'strategy': strat_info['label'], 'model': strat_info['model'],
            'symbol': symbol, 'rank': strat_info['rank'],
            'origin_arr': strat_info['origin_arr'],
            'return_pct': None, 'sharpe_ratio': None,
            'avg_annual': None, 'max_drawdown': None, 'status': 'error',
        })
        continue

    print(f"Running: {strat_info['label']}", end='  ')
    try:
        ret, sharpe, avg_ann, max_dd = bt_instance.timed_backtest(
            strategy_cls, symbol, BENCHMARK_START, BENCHMARK_END
        )
        status = 'profitable' if ret > 0 else ('no_trades' if ret == 0 and sharpe is None else 'loss')
        print(f"ARR={avg_ann:.1f}%  SHR={sharpe}  MDD={max_dd:.1f}%  [{status}]")
    except Exception as e:
        ret, sharpe, avg_ann, max_dd, status = None, None, None, None, 'error'
        print(f"ERROR — {str(e)[:80]}")

    all_results.append({
        'strategy':     strat_info['label'],
        'model':        strat_info['model'],
        'symbol':       symbol,
        'rank':         strat_info['rank'],
        'origin_arr':   strat_info['origin_arr'],
        'return_pct':   ret,
        'sharpe_ratio': sharpe,
        'avg_annual':   avg_ann,
        'max_drawdown': max_dd,
        'status':       status,
    })

df_all = pd.DataFrame(all_results)

# Keep best per model × symbol: profitable > loss > no_trades/error, then highest avg_annual
status_priority = {'profitable': 0, 'loss': 1, 'no_trades': 2, 'error': 3}
df_all['_sp'] = df_all['status'].map(status_priority).fillna(3)
df_bench = (
    df_all
    .sort_values(['model', 'symbol', '_sp', 'avg_annual'], ascending=[True, True, True, False])
    .groupby(['model', 'symbol'])
    .first()
    .reset_index()
    .drop(columns='_sp')
)

print(f'\nDone. {len(df_all)} candidates → {len(df_bench)} best results.')

Running: Qwen2.5-7B LoRA v1-500 [AAPL] #1  ARR=25.4%  SHR=1.340502006858562  MDD=15.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AAPL] #2  ARR=25.2%  SHR=1.3443698092183263  MDD=15.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AAPL] #3  ARR=0.8%  SHR=-0.008381979584730657  MDD=27.2%  [loss]
Running: Qwen2.5-7B LoRA v1-500 [AAPL] #4  ARR=3.7%  SHR=0.10465846642483038  MDD=23.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AAPL] #5  ARR=3.7%  SHR=0.10465846642483038  MDD=23.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AAPL] #6  ARR=3.7%  SHR=0.10465846642483038  MDD=23.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AAPL] #7  ARR=3.9%  SHR=0.11182169114233079  MDD=23.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AAPL] #8  ARR=10.7%  SHR=0.9065193411483164  MDD=14.8%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AMZN] #1  ARR=14.9%  SHR=0.518056431732826  MDD=20.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AMZN] #2  ARR=14.9%  SHR=0.518056431732826  MDD=20.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AMZN] #3  ARR=14.9%  SHR=0.518056431732826  MDD=20.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AMZN] #4  ARR=12.5%  SHR=0.9200057595853098  MDD=17.4%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AMZN] #5  ARR=19.0%  SHR=1.6172862199745306  MDD=22.2%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AMZN] #6  ARR=6.5%  SHR=0.8457492345305762  MDD=22.5%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [AMZN] #7  ARR=3.7%  SHR=0.14911072281406806  MDD=25.7%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [MSFT] #1  ARR=15.4%  SHR=0.5843947923920801  MDD=14.8%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [MSFT] #2  ARR=15.4%  SHR=0.5843947923920801  MDD=14.8%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [MSFT] #3  ARR=15.4%  SHR=0.5843947923920801  MDD=14.8%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [MSFT] #4  ARR=23.3%  SHR=0.7028823086264485  MDD=25.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [MSFT] #5  ARR=15.4%  SHR=0.5843947923920801  MDD=14.8%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [MSFT] #6  ARR=15.4%  SHR=0.5843947923920801  MDD=14.8%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [MSFT] #7  ARR=12.1%  SHR=0.7550284922322533  MDD=12.1%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [TSLA] #1  ARR=16.5%  SHR=0.24074637441399804  MDD=54.4%  [loss]
Running: Qwen2.5-7B LoRA v1-500 [TSLA] #2  ARR=-2.0%  SHR=-0.7154462229394869  MDD=41.7%  [loss]
Running: Qwen2.5-7B LoRA v1-500 [TSLA] #3  ARR=-2.0%  SHR=-0.7154462229394869  MDD=41.7%  [loss]
Running: Qwen2.5-7B LoRA v1-500 [TSLA] #4  ARR=-2.0%  SHR=-0.7154462229394869  MDD=41.7%  [loss]
Running: Qwen2.5-7B LoRA v1-500 [TSLA] #5  ARR=-2.0%  SHR=-0.7154462229394869  MDD=41.7%  [loss]
Running: Qwen2.5-7B LoRA v1-500 [TSLA] #6  ARR=12.1%  SHR=4.225038486226837  MDD=32.5%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [TSLA] #7  ARR=12.9%  SHR=0.9221865577278474  MDD=15.7%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [TSLA] #8  ARR=0.3%  SHR=-2.746019853905241  MDD=35.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [GOOGL] #1  ARR=16.1%  SHR=0.9379344587884806  MDD=13.0%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [GOOGL] #2  ARR=6.2%  SHR=0.8386901641327573  MDD=14.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [GOOGL] #3  ARR=5.7%  SHR=0.2159821505810797  MDD=21.1%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [GOOGL] #4  ARR=-11.6%  SHR=-2.047828066039934  MDD=25.0%  [loss]
Running: Qwen2.5-7B LoRA v1-500 [GOOGL] #5  ARR=-11.6%  SHR=-2.047828066039934  MDD=25.0%  [loss]
Running: Qwen2.5-7B LoRA v1-500 [GOOGL] #6  ARR=-11.6%  SHR=-2.047828066039934  MDD=25.0%  [loss]
Running: Qwen2.5-7B LoRA v1-500 [GOOGL] #7  ARR=-2.8%  SHR=-0.5688735529493248  MDD=20.8%  [loss]
Running: Qwen2.5-7B LoRA v1-500 [GOOGL] #8  ARR=2.9%  SHR=0.08136578662820802  MDD=24.6%  [profitable]
Running: Qwen2.5-7B LoRA v1-500 [GOOGL] #9  ARR=-4.7%  SHR=-1.3613979220473413  MDD=12.4%  [loss]
Running: Llama-3.1-8B LoRA v1-500 [AMZN] #1  ARR=0.2%  SHR=-1.720968330277785  MDD=0.6%  [profitable]
Running: Llama-3.1-8B LoRA v1-500 [AMZN] #2  ARR=0.1%  SHR=-1.5010544125820495  MDD=0.6%  [profitable]
Running: Llama-3.1-8B LoRA v1-500 [MSFT] #1  ARR=4.8%  SHR=0.27735725318675186  MDD=13.7%  [profitable]
Running: Llama-3.1-8B LoRA v1-500 [MSFT] #2  ARR=0.2%  SHR=-0.8830132234491672  MDD=0.7%  [profitable]
Running: Llama-3.1-8B LoRA v1-500 [TSLA] #1  ARR=-1.8%  SHR=-1.5505698397841843  MDD=29.1%  [loss]
Running: Llama-3.1-8B LoRA v1-500 [TSLA] #2  ARR=21.3%  SHR=0.2577985162996616  MDD=64.0%  [loss]
Running: Llama-3.1-8B LoRA v1-500 [TSLA] #3  ARR=1.0%  SHR=0.003813119593309894  MDD=17.0%  [profitable]
Running: Llama-3.1-8B LoRA v1-500 [TSLA] #4  ARR=0.3%  SHR=-1.0708741018371122  MDD=1.1%  [profitable]
Running: Llama-3.1-8B LoRA v1-500 [TSLA] #5  ARR=-0.2%  SHR=-0.8845480720676956  MDD=1.9%  [loss]
Running: Llama-3.1-8B LoRA v1-500 [GOOGL] #1  ARR=-0.7%  SHR=-2.004075256285965  MDD=8.9%  [loss]
Running: Llama-3.1-8B LoRA v1-500 [GOOGL] #2  ARR=0.1%  SHR=-9.415708279055165  MDD=0.2%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [AAPL] #1  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [AAPL] #2  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [AAPL] #3  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [AAPL] #4  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [AAPL] #5  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [AAPL] #6  ARR=14.1%  SHR=0.8550615053255031  MDD=19.2%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [AAPL] #7  ARR=25.2%  SHR=1.3443698092183263  MDD=15.6%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [AAPL] #8  ARR=7.4%  SHR=0.36166070887763935  MDD=13.0%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [AAPL] #9  ARR=14.1%  SHR=0.8550615053255031  MDD=19.2%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [AAPL] #10  ARR=-1.9%  SHR=-0.1389596101411678  MDD=27.6%  [loss]
Running: Qwen2.5-32B LoRA v1-500 [AMZN] #1  ARR=20.8%  SHR=0.6157622986867446  MDD=30.8%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [AMZN] #2  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [AMZN] #3  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [AMZN] #4  ARR=8.1%  SHR=0.4103701778604486  MDD=18.8%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [AMZN] #5  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [AMZN] #6  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [AMZN] #7  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [AMZN] #8  ARR=25.1%  SHR=0.4883666150291615  MDD=41.4%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [AMZN] #9  ARR=10.6%  SHR=0.38322475071650874  MDD=18.4%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [AMZN] #10  ARR=11.6%  SHR=0.2660342305324032  MDD=32.8%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [MSFT] #1  ARR=20.3%  SHR=0.5302117989957833  MDD=26.3%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [MSFT] #2  ARR=20.3%  SHR=0.5302117989957833  MDD=26.3%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [MSFT] #3  ARR=18.7%  SHR=0.9465605001937182  MDD=12.9%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [MSFT] #4  ARR=26.0%  SHR=0.78847128175757  MDD=26.6%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [MSFT] #5  ARR=25.2%  SHR=0.7740100250924257  MDD=26.2%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [MSFT] #6  ARR=20.3%  SHR=0.5302117989957833  MDD=26.3%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [MSFT] #7  ARR=20.3%  SHR=0.5302117989957833  MDD=26.3%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [MSFT] #8  ARR=13.1%  SHR=0.7876953930222302  MDD=16.9%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [MSFT] #9  ARR=18.7%  SHR=0.9465605001937182  MDD=12.9%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [MSFT] #10  ARR=11.6%  SHR=0.44122620321147843  MDD=19.0%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [TSLA] #1  ARR=24.7%  SHR=0.3286359272664979  MDD=54.5%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [TSLA] #2  ARR=25.4%  SHR=0.34577255573465715  MDD=63.5%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [TSLA] #3  ARR=20.7%  SHR=0.25541218756724593  MDD=64.1%  [loss]
Running: Qwen2.5-32B LoRA v1-500 [TSLA] #4  ARR=20.7%  SHR=0.25541218756724593  MDD=64.1%  [loss]
Running: Qwen2.5-32B LoRA v1-500 [TSLA] #5  ARR=20.7%  SHR=0.25541218756724593  MDD=64.1%  [loss]
Running: Qwen2.5-32B LoRA v1-500 [TSLA] #6  ARR=20.7%  SHR=0.25541218756724593  MDD=64.1%  [loss]
Running: Qwen2.5-32B LoRA v1-500 [TSLA] #7  ARR=25.4%  SHR=0.34577255573465715  MDD=63.5%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [TSLA] #8  ARR=25.4%  SHR=0.33244599163338484  MDD=64.2%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [TSLA] #9  ARR=10.1%  SHR=1.463406054381549  MDD=31.1%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [TSLA] #10  ARR=-7.6%  SHR=-23.646627551702405  MDD=36.0%  [loss]
Running: Qwen2.5-32B LoRA v1-500 [GOOGL] #1  ARR=27.4%  SHR=0.9635123054749786  MDD=12.9%  [profitable]
Running: Qwen2.5-32B LoRA v1-500 [GOOGL] #2  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [GOOGL] #3  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [GOOGL] #4  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [GOOGL] #5  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [GOOGL] #6  ARR=0.0%  SHR=None  MDD=0.0%  [no_trades]
Running: Qwen2.5-32B LoRA v1-500 [GOOGL] #7  ARR=-1.4%  SHR=-0.21355530252410482  MDD=25.1%  [loss]
Running: Qwen2.5-32B LoRA v1-500 [GOOGL] #8  ARR=-8.6%  SHR=-1.620899611866419  MDD=22.2%  [loss]
Running: Qwen2.5-32B LoRA v1-500 [GOOGL] #9  ARR=-9.5%  SHR=-0.8939553375873864  MDD=27.1%  [loss]
Running: Qwen2.5-32B LoRA v1-500 [GOOGL] #10  ARR=-9.6%  SHR=-0.8883601772872133  MDD=27.3%  [loss]

Done. 100 candidates → 14 best results.

### Results Table

In [111]:
for metric, col in [
    ('ARR — Avg Annual Return %', 'avg_annual'),
    ('SHR — Sharpe Ratio',        'sharpe_ratio'),
    ('MDD — Max Drawdown %',      'max_drawdown'),
]:
    pivot = df_bench.pivot_table(
        index='model', columns='symbol', values=col
    ).round(3)
    pivot['Avg'] = pivot.mean(axis=1).round(3)
    pivot = pivot.sort_values('Avg', ascending=(col == 'max_drawdown'))
    print(f'\n=== {metric} ===')
    display(pivot)

=== ARR — Avg Annual Return % ===

symbol                      AAPL    AMZN   GOOGL    MSFT    TSLA     Avg
model
Qwen2.5-32B LoRA v1-500   25.227  25.096  27.406  25.989  25.413  25.826
Qwen2.5-7B LoRA v1-500    25.431  19.027  16.112  23.261  12.851  19.336
Llama-3.1-8B LoRA v1-500     NaN   0.238   0.085   4.848   1.044   1.554

=== SHR — Sharpe Ratio ===

symbol                     AAPL   AMZN  GOOGL   MSFT   TSLA    Avg
model
Qwen2.5-7B LoRA v1-500    1.341  1.617  0.938  0.703  0.922  1.104
Qwen2.5-32B LoRA v1-500   1.344  0.488  0.964  0.788  0.346  0.786
Llama-3.1-8B LoRA v1-500    NaN -1.721 -9.416  0.277  0.004 -2.714

=== MDD — Max Drawdown % ===

symbol                      AAPL    AMZN   GOOGL    MSFT    TSLA     Avg
model
Llama-3.1-8B LoRA v1-500     NaN   0.627   0.176  13.727  17.046   7.894
Qwen2.5-7B LoRA v1-500    15.567  22.156  13.017  25.596  15.724  18.412
Qwen2.5-32B LoRA v1-500   15.567  41.407  12.874  26.649  63.549  32.009

### Save Results

In [112]:
df_bench.to_csv('strategy_benchmark_results.csv', index=False)
print('Saved to strategy_benchmark_results.csv')
display(df_bench[['model', 'symbol', 'avg_annual', 'sharpe_ratio', 'max_drawdown', 'status']].rename(columns={
    'avg_annual':   'ARR %',
    'sharpe_ratio': 'SHR',
    'max_drawdown': 'MDD %',
}).round(3))

Saved to strategy_benchmark_results.csv

                       model symbol   ARR %    SHR   MDD %      status
0   Llama-3.1-8B LoRA v1-500   AMZN   0.238 -1.721   0.627  profitable
1   Llama-3.1-8B LoRA v1-500  GOOGL   0.085 -9.416   0.176  profitable
2   Llama-3.1-8B LoRA v1-500   MSFT   4.848  0.277  13.727  profitable
3   Llama-3.1-8B LoRA v1-500   TSLA   1.044  0.004  17.046  profitable
4    Qwen2.5-32B LoRA v1-500   AAPL  25.227  1.344  15.567  profitable
5    Qwen2.5-32B LoRA v1-500   AMZN  25.096  0.488  41.407  profitable
6    Qwen2.5-32B LoRA v1-500  GOOGL  27.406  0.964  12.874  profitable
7    Qwen2.5-32B LoRA v1-500   MSFT  25.989  0.788  26.649  profitable
8    Qwen2.5-32B LoRA v1-500   TSLA  25.413  0.346  63.549  profitable
9     Qwen2.5-7B LoRA v1-500   AAPL  25.431  1.341  15.567  profitable
10    Qwen2.5-7B LoRA v1-500   AMZN  19.027  1.617  22.156  profitable
11    Qwen2.5-7B LoRA v1-500  GOOGL  16.112  0.938  13.017  profitable
12    Qwen2.5-7B LoRA v1-500   MSFT  23.261  0.703  25.596  profitable
13    Qwen2.5-7B LoRA v1-500   TSLA  12.851  0.922  15.724  profitable